### ISSUE TITLE
issue closed

### ISSUE THREAD

**Issue by Willy030125** [Questandachievement7Developer/RaiseTheEmpiresPort_Native#2]
![Screenshot (245)](https://user-images.githubusercontent.com/59504241/76417515-92c53800-63cf-11ea-9a26-0954c818c715.png)
![Screenshot (247)](https://user-images.githubusercontent.com/59504241/76417537-9b1d7300-63cf-11ea-9859-de5cbe1eeaf6.png)
![Screenshot (248)](https://user-images.githubusercontent.com/59504241/76417547-9f499080-63cf-11ea-8fbf-7285ba96e147.png)

**Comment by Questandachievement7Developer** [comment]
time to yeet the sudo  problems

Note : This was running in WSL unifyServer Container (Project Bay)
Thank you for the feedback
